# Generated by Django 4.0.4 on 2022-07-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(blank=True, max_length=15, null=True)),
                ('tech_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(default='torik135', max_length=50)),
                ('project_desc', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('web_link', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('FE', 'Front End'), ('BE', 'Back End'), ('FS', 'Full Stack'), ('PL', 'Plain / Native')], max_length=150, null=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_portofolio.techchoices')),
            ],
        ),
    ]
