# Generated by Django 4.0.4 on 2022-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='tech',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='tech',
            field=models.ManyToManyField(to='app_portofolio.techchoices'),
        ),
    ]
