# Generated by Django 4.0.4 on 2022-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0002_remove_projectlist_tech_projectlist_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techchoices',
            name='tech_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
