# Generated by Django 4.0.4 on 2022-07-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0004_projectlist_project_img_alter_projectlist_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
